name: Generate terraform docs
on:
  push:
    paths:
      - '**/*.tf'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Render terraform docs inside the README.md and push changes
      uses: terraform-docs/gh-actions@v1.3.0 
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"